### ISSUE TITLE
Exception Throw when using in Blazor Server

### ISSUE THREAD

**Issue by nunonux** [KristofferStrube/Blazor.Popper#1]
Hi there and thank you for building this library. I'm doing a project with Blazor Server and when I try to use it an exception is thrown as bellow:

 Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Deserialization of interface types is not supported. Type 'Microsoft.JSInterop.IJSInProcessObjectReference'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.. See InnerException for more details.
 ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'Microsoft.JSInterop.IJSInProcessObjectReference'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'Microsoft.JSInterop.IJSInProcessObjectReference'.

I could it be because of the type of Blazor I'm using?

**Comment by KristofferStrube** [comment]
Hey @nunonux,
I had not tested the library in Blazor Server for newer versions. I see that it does not work with Blazor Server after a quick test. I will update this in the readme.
Thanks for noticing.
