### ISSUE TITLE
How to invoke popper for target in a foreach loop

### ISSUE THREAD

**Issue by Liero** [KristofferStrube/Blazor.Popper#2]
Hi Kristoffer,

_I was just about to write a popper interop and found yours. Thanks for a good work!._

Would you be so kind and provide a sample on how to invoke popper for a reference in a foreach loop?

```razor
foreach(var item in Items)
{
   <button type="button" id="reference" @ref=??? aria-describedby="tooltip"
                  @onclick="_ => new Popper(???, tooltip)">
      @item
   </button>
}
<div id="popper" @ref=tooltip role="tooltip" style="height:50px;width:100px;">
    Popper
</div>
```

also, do you have some guidance regarding disposing / destroying the instance?

**Comment by KristofferStrube** [comment]
Hey @Liero 
I would recommend creating a component for each button with its own popper. Else you would need a list of `ElementReference`'s for each popper and button.

I'm working on adding an example for that in the demo right now. It will be up later today.

**Comment by KristofferStrube** [comment]
@Liero 
I have added this as an example now where I use a component to encapsulate each button functionality: https://kristofferstrube.github.io/Blazor.Popper/ForLoop 

Please let me know if the example is useful.

The `Instance` has a `Destroy` function that can be called if you want to destroy the popper when e.g. disposing of a component.
